//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace conexionBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class proveedor
    {
        public int id { get; set; }
        public int id_per { get; set; }
        public string Politica_venta { get; set; }
        public string Tiempo_entrega { get; set; }
        public string Observacion { get; set; }
        public string SitioWeb { get; set; }
        public string Estado { get; set; }
    
        public virtual persona persona { get; set; }
    }
}
