//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace conexionBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class traslado_producto
    {
        public int id_traslado { get; set; }
        public string fechaTraslado { get; set; }
        public string fechaModificacion { get; set; }
        public string id_almacenOrigen { get; set; }
        public string id_almacenDestino { get; set; }
        public string id_motivo { get; set; }
        public string estado { get; set; }
    }
}
