//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace conexionBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public int id { get; set; }
        public int id_sur { get; set; }
        public int id_asig { get; set; }
        public string Name_User { get; set; }
        public string Pass { get; set; }
    
        public virtual asignar_cargo asignar_cargo { get; set; }
        public virtual sucursal sucursal { get; set; }
    }
}
